# Development environment configuration
# This file contains settings specific to the development environment

spring:
  # Development-specific settings
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true
  
  # Database configuration for development
  datasource:
    url: jdbc:mysql://localhost:3307/taskflow_dev?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME:dev_user}
    password: ${DB_PASSWORD:dev_pass}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA configuration for development
  jpa:
    hibernate:
      ddl-auto: create-drop  # Recrea las tablas en cada inicio
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
        use_sql_comments: true

# Logging for development
logging:
  level:
    root: INFO
    com.taskflow: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Application specific settings
app:
  name: TaskFlow API
  version: 0.0.1-SNAPSHOT
  description: Task Management REST API - Development Environment

