# TaskFlow API Configuration
# This is the main configuration file for our Spring Boot application

spring:
  application:
    name: taskflow-api
  
  profiles:
    active: dev

# Server configuration
server:
  port: 8080
  servlet:
    context-path: /api/v1

# Logging configuration
logging:
  level:
    com.taskflow: DEBUG
    org.springframework.web: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Management endpoints for monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

